### ISSUE TITLE
Anonymous user cannot create a post.

### ISSUE THREAD

**Issue by muremwa** [alexmuriukimaina/blog-app#2]
When a an anonymous user edits or creates a post, the site will crash.

**Comment by alexmuriukimaina** [comment]
Thanks bro. I'll work on it

**Comment by muremwa** [comment]
I already did. #1

**Comment by alexmuriukimaina** [comment]
Thanks

**Comment by muremwa** [comment]
Go [here](https://github.com/alexmuriukimaina/blog-app/pull/1) and merge to close this issue!
